name: Release

on:
  push:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-java@v3"
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradel
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build
      - name: Shadow Jar
        run: ./gradlew shadowJar
