name: Revision Update
on:
  schedule:
    - cron: 0/30 * * * *

jobs:
  revision_update:
    name: Revision Update
    runs-on: ubuntu-latest
    needs: fetch_revisions
    env:
      CREATE_RELEASE: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Check for Revision Updates
        id: check_revision_updates
        env:
          LATEST_REV: ${{ needs.fetch_revisions.outputs.latest_rev }}
        run: |
          sudo apt-get update
          sudo apt-get install git -y
          cd $GITHUB_WORKSPACE
          git fetch --tags
          git fetch --prune --unshallow || true
          export CURRENT_REV=$(git describe --abbrev=0 --tags)
          current="$CURRENT_REV"
          latest="$LATEST_REV"
          
          if [ "$current" != "$latest" ]; then
            echo "Repository revision release is out-of-date. Current: $CURRENT_REV, Latest: $LATEST_REV"
            echo "::set-output name=create-release::TRUE"
            echo "CREATE_RELEASE=TRUE" >> "$GITHUB_ENV"
          else
            echo "Repository revision is up-to-date. Current: $CURRENT_REV, Latest: $LATEST_REV"
            echo "::set-output name=create-release::FALSE"
            echo "CREATE_RELEASE=FALSE" >> "$GITHUB_ENV"
          fi
        shell: bash
      - name: Download Latest Gamepack Revision
        if: env.CREATE_RELEASE == 'true'
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p out/
          curl -sL https://github.com/spectral-powered/osrs-gamepacks/releases/download/v1.0.0/gamepack-downloader.jar -o gamepack-downloader.jar
          java -jar gamepack-downloader.jar download out/gamepack.jar
      - name: Create Revision Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.fetch_revisions.outputs.latest_rev }}
          release_name: Revision ${{ needs.fetch_revisions.outputs.latest_rev }}
          draft: false
          prerelease: false
      - name: Upload Gamepack Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/gamepack.jar
          asset_name: gamepack.jar
          asset_content_type: application/zip
  fetch_revisions:
    name: Fetch Revisions
    runs-on: ubuntu-latest
    outputs:
      current_rev: ${{ steps.gamepack.outputs.current }}
      latest_rev: ${{ steps.gamepack.outputs.latest }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Fetch Revisions
        id: gamepack
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p out/
          curl -sL https://github.com/spectral-powered/osrs-gamepacks/releases/download/v1.0.0/gamepack-downloader.jar -o gamepack-downloader.jar
          LATEST_REV=$(java -jar gamepack-downloader.jar revision)
          echo "::set-output name=latest::$LATEST_REV"
        
    
